[package]
name = "UltimateList"
version = "0.2.4"
files = [
    "src/**",
    "!*.spec.lua",
    "!*.story.lua",
]
publish = true

[config]
registry_index = true

[dependencies]
React = "github.com/roblox/roact-alignment@^17.3.7"
